# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='null', max_length=45)),
                ('last_name', models.CharField(default='null', max_length=45)),
                ('email', models.CharField(default='null', max_length=45)),
                ('password', models.CharField(default='null', max_length=255)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
