# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.User')),
            ],
        ),
    ]
